### ISSUE TITLE
useUserSelectorHook

### ISSUE THREAD

**Issue by iPhaeton** [janglewood/todo_test#3]
1. You create `accordingUser` inside `useUserSelectorHook`. So it is effectively not memoized, because it is created on every `useUserSelectorHook` run. You should create it outside `useUserSelectorHook`. I think, it should be define in `src/selectors` folder.
2. Also `accordingUser` is not the best name for a selector. Try to start selector names with "get" when appropriate. For example `getUserByUserId`.

**Comment by janglewood** [comment]
Resolved
